module Ruboty
  module Handlers
    class Ghibli < Base
      PICTURES = %w[
        http://www.ghibli.jp/gallery/marnie001.jpg
        http://www.ghibli.jp/gallery/marnie002.jpg
        http://www.ghibli.jp/gallery/marnie003.jpg
        http://www.ghibli.jp/gallery/marnie004.jpg
        http://www.ghibli.jp/gallery/marnie005.jpg
        http://www.ghibli.jp/gallery/marnie006.jpg
        http://www.ghibli.jp/gallery/marnie007.jpg
        http://www.ghibli.jp/gallery/marnie008.jpg
        http://www.ghibli.jp/gallery/marnie009.jpg
        http://www.ghibli.jp/gallery/marnie010.jpg
        http://www.ghibli.jp/gallery/marnie011.jpg
        http://www.ghibli.jp/gallery/marnie012.jpg
        http://www.ghibli.jp/gallery/marnie013.jpg
        http://www.ghibli.jp/gallery/marnie014.jpg
        http://www.ghibli.jp/gallery/marnie015.jpg
        http://www.ghibli.jp/gallery/marnie016.jpg
        http://www.ghibli.jp/gallery/marnie017.jpg
        http://www.ghibli.jp/gallery/marnie018.jpg
        http://www.ghibli.jp/gallery/marnie019.jpg
        http://www.ghibli.jp/gallery/marnie020.jpg
        http://www.ghibli.jp/gallery/marnie021.jpg
        http://www.ghibli.jp/gallery/marnie022.jpg
        http://www.ghibli.jp/gallery/marnie023.jpg
        http://www.ghibli.jp/gallery/marnie024.jpg
        http://www.ghibli.jp/gallery/marnie025.jpg
        http://www.ghibli.jp/gallery/marnie026.jpg
        http://www.ghibli.jp/gallery/marnie027.jpg
        http://www.ghibli.jp/gallery/marnie028.jpg
        http://www.ghibli.jp/gallery/marnie029.jpg
        http://www.ghibli.jp/gallery/marnie030.jpg
        http://www.ghibli.jp/gallery/marnie031.jpg
        http://www.ghibli.jp/gallery/marnie032.jpg
        http://www.ghibli.jp/gallery/marnie033.jpg
        http://www.ghibli.jp/gallery/marnie034.jpg
        http://www.ghibli.jp/gallery/marnie035.jpg
        http://www.ghibli.jp/gallery/marnie036.jpg
        http://www.ghibli.jp/gallery/marnie037.jpg
        http://www.ghibli.jp/gallery/marnie038.jpg
        http://www.ghibli.jp/gallery/marnie039.jpg
        http://www.ghibli.jp/gallery/marnie040.jpg
        http://www.ghibli.jp/gallery/marnie041.jpg
        http://www.ghibli.jp/gallery/marnie042.jpg
        http://www.ghibli.jp/gallery/marnie043.jpg
        http://www.ghibli.jp/gallery/marnie044.jpg
        http://www.ghibli.jp/gallery/marnie045.jpg
        http://www.ghibli.jp/gallery/marnie046.jpg
        http://www.ghibli.jp/gallery/marnie047.jpg
        http://www.ghibli.jp/gallery/marnie048.jpg
        http://www.ghibli.jp/gallery/marnie049.jpg
        http://www.ghibli.jp/gallery/marnie050.jpg

        http://www.ghibli.jp/gallery/kaguyahime001.jpg
        http://www.ghibli.jp/gallery/kaguyahime002.jpg
        http://www.ghibli.jp/gallery/kaguyahime003.jpg
        http://www.ghibli.jp/gallery/kaguyahime004.jpg
        http://www.ghibli.jp/gallery/kaguyahime005.jpg
        http://www.ghibli.jp/gallery/kaguyahime006.jpg
        http://www.ghibli.jp/gallery/kaguyahime007.jpg
        http://www.ghibli.jp/gallery/kaguyahime008.jpg
        http://www.ghibli.jp/gallery/kaguyahime009.jpg
        http://www.ghibli.jp/gallery/kaguyahime010.jpg
        http://www.ghibli.jp/gallery/kaguyahime011.jpg
        http://www.ghibli.jp/gallery/kaguyahime012.jpg
        http://www.ghibli.jp/gallery/kaguyahime013.jpg
        http://www.ghibli.jp/gallery/kaguyahime014.jpg
        http://www.ghibli.jp/gallery/kaguyahime015.jpg
        http://www.ghibli.jp/gallery/kaguyahime016.jpg
        http://www.ghibli.jp/gallery/kaguyahime017.jpg
        http://www.ghibli.jp/gallery/kaguyahime018.jpg
        http://www.ghibli.jp/gallery/kaguyahime019.jpg
        http://www.ghibli.jp/gallery/kaguyahime020.jpg
        http://www.ghibli.jp/gallery/kaguyahime021.jpg
        http://www.ghibli.jp/gallery/kaguyahime022.jpg
        http://www.ghibli.jp/gallery/kaguyahime023.jpg
        http://www.ghibli.jp/gallery/kaguyahime024.jpg
        http://www.ghibli.jp/gallery/kaguyahime025.jpg
        http://www.ghibli.jp/gallery/kaguyahime026.jpg
        http://www.ghibli.jp/gallery/kaguyahime027.jpg
        http://www.ghibli.jp/gallery/kaguyahime028.jpg
        http://www.ghibli.jp/gallery/kaguyahime029.jpg
        http://www.ghibli.jp/gallery/kaguyahime030.jpg
        http://www.ghibli.jp/gallery/kaguyahime031.jpg
        http://www.ghibli.jp/gallery/kaguyahime032.jpg
        http://www.ghibli.jp/gallery/kaguyahime033.jpg
        http://www.ghibli.jp/gallery/kaguyahime034.jpg
        http://www.ghibli.jp/gallery/kaguyahime035.jpg
        http://www.ghibli.jp/gallery/kaguyahime036.jpg
        http://www.ghibli.jp/gallery/kaguyahime037.jpg
        http://www.ghibli.jp/gallery/kaguyahime038.jpg
        http://www.ghibli.jp/gallery/kaguyahime039.jpg
        http://www.ghibli.jp/gallery/kaguyahime040.jpg
        http://www.ghibli.jp/gallery/kaguyahime041.jpg
        http://www.ghibli.jp/gallery/kaguyahime042.jpg
        http://www.ghibli.jp/gallery/kaguyahime043.jpg
        http://www.ghibli.jp/gallery/kaguyahime044.jpg
        http://www.ghibli.jp/gallery/kaguyahime045.jpg
        http://www.ghibli.jp/gallery/kaguyahime046.jpg
        http://www.ghibli.jp/gallery/kaguyahime047.jpg
        http://www.ghibli.jp/gallery/kaguyahime048.jpg
        http://www.ghibli.jp/gallery/kaguyahime049.jpg
        http://www.ghibli.jp/gallery/kaguyahime050.jpg

        http://www.ghibli.jp/gallery/kazetachinu001.jpg
        http://www.ghibli.jp/gallery/kazetachinu002.jpg
        http://www.ghibli.jp/gallery/kazetachinu003.jpg
        http://www.ghibli.jp/gallery/kazetachinu004.jpg
        http://www.ghibli.jp/gallery/kazetachinu005.jpg
        http://www.ghibli.jp/gallery/kazetachinu006.jpg
        http://www.ghibli.jp/gallery/kazetachinu007.jpg
        http://www.ghibli.jp/gallery/kazetachinu008.jpg
        http://www.ghibli.jp/gallery/kazetachinu009.jpg
        http://www.ghibli.jp/gallery/kazetachinu010.jpg
        http://www.ghibli.jp/gallery/kazetachinu011.jpg
        http://www.ghibli.jp/gallery/kazetachinu012.jpg
        http://www.ghibli.jp/gallery/kazetachinu013.jpg
        http://www.ghibli.jp/gallery/kazetachinu014.jpg
        http://www.ghibli.jp/gallery/kazetachinu015.jpg
        http://www.ghibli.jp/gallery/kazetachinu016.jpg
        http://www.ghibli.jp/gallery/kazetachinu017.jpg
        http://www.ghibli.jp/gallery/kazetachinu018.jpg
        http://www.ghibli.jp/gallery/kazetachinu019.jpg
        http://www.ghibli.jp/gallery/kazetachinu020.jpg
        http://www.ghibli.jp/gallery/kazetachinu021.jpg
        http://www.ghibli.jp/gallery/kazetachinu022.jpg
        http://www.ghibli.jp/gallery/kazetachinu023.jpg
        http://www.ghibli.jp/gallery/kazetachinu024.jpg
        http://www.ghibli.jp/gallery/kazetachinu025.jpg
        http://www.ghibli.jp/gallery/kazetachinu026.jpg
        http://www.ghibli.jp/gallery/kazetachinu027.jpg
        http://www.ghibli.jp/gallery/kazetachinu028.jpg
        http://www.ghibli.jp/gallery/kazetachinu029.jpg
        http://www.ghibli.jp/gallery/kazetachinu030.jpg
        http://www.ghibli.jp/gallery/kazetachinu031.jpg
        http://www.ghibli.jp/gallery/kazetachinu032.jpg
        http://www.ghibli.jp/gallery/kazetachinu033.jpg
        http://www.ghibli.jp/gallery/kazetachinu034.jpg
        http://www.ghibli.jp/gallery/kazetachinu035.jpg
        http://www.ghibli.jp/gallery/kazetachinu036.jpg
        http://www.ghibli.jp/gallery/kazetachinu037.jpg
        http://www.ghibli.jp/gallery/kazetachinu038.jpg
        http://www.ghibli.jp/gallery/kazetachinu039.jpg
        http://www.ghibli.jp/gallery/kazetachinu040.jpg
        http://www.ghibli.jp/gallery/kazetachinu041.jpg
        http://www.ghibli.jp/gallery/kazetachinu042.jpg
        http://www.ghibli.jp/gallery/kazetachinu043.jpg
        http://www.ghibli.jp/gallery/kazetachinu044.jpg
        http://www.ghibli.jp/gallery/kazetachinu045.jpg
        http://www.ghibli.jp/gallery/kazetachinu046.jpg
        http://www.ghibli.jp/gallery/kazetachinu047.jpg
        http://www.ghibli.jp/gallery/kazetachinu048.jpg
        http://www.ghibli.jp/gallery/kazetachinu049.jpg
        http://www.ghibli.jp/gallery/kazetachinu050.jpg

        http://www.ghibli.jp/gallery/kokurikozaka001.jpg
        http://www.ghibli.jp/gallery/kokurikozaka002.jpg
        http://www.ghibli.jp/gallery/kokurikozaka003.jpg
        http://www.ghibli.jp/gallery/kokurikozaka004.jpg
        http://www.ghibli.jp/gallery/kokurikozaka005.jpg
        http://www.ghibli.jp/gallery/kokurikozaka006.jpg
        http://www.ghibli.jp/gallery/kokurikozaka007.jpg
        http://www.ghibli.jp/gallery/kokurikozaka008.jpg
        http://www.ghibli.jp/gallery/kokurikozaka009.jpg
        http://www.ghibli.jp/gallery/kokurikozaka010.jpg
        http://www.ghibli.jp/gallery/kokurikozaka011.jpg
        http://www.ghibli.jp/gallery/kokurikozaka012.jpg
        http://www.ghibli.jp/gallery/kokurikozaka013.jpg
        http://www.ghibli.jp/gallery/kokurikozaka014.jpg
        http://www.ghibli.jp/gallery/kokurikozaka015.jpg
        http://www.ghibli.jp/gallery/kokurikozaka016.jpg
        http://www.ghibli.jp/gallery/kokurikozaka017.jpg
        http://www.ghibli.jp/gallery/kokurikozaka018.jpg
        http://www.ghibli.jp/gallery/kokurikozaka019.jpg
        http://www.ghibli.jp/gallery/kokurikozaka020.jpg
        http://www.ghibli.jp/gallery/kokurikozaka021.jpg
        http://www.ghibli.jp/gallery/kokurikozaka022.jpg
        http://www.ghibli.jp/gallery/kokurikozaka023.jpg
        http://www.ghibli.jp/gallery/kokurikozaka024.jpg
        http://www.ghibli.jp/gallery/kokurikozaka025.jpg
        http://www.ghibli.jp/gallery/kokurikozaka026.jpg
        http://www.ghibli.jp/gallery/kokurikozaka027.jpg
        http://www.ghibli.jp/gallery/kokurikozaka028.jpg
        http://www.ghibli.jp/gallery/kokurikozaka029.jpg
        http://www.ghibli.jp/gallery/kokurikozaka030.jpg
        http://www.ghibli.jp/gallery/kokurikozaka031.jpg
        http://www.ghibli.jp/gallery/kokurikozaka032.jpg
        http://www.ghibli.jp/gallery/kokurikozaka033.jpg
        http://www.ghibli.jp/gallery/kokurikozaka034.jpg
        http://www.ghibli.jp/gallery/kokurikozaka035.jpg
        http://www.ghibli.jp/gallery/kokurikozaka036.jpg
        http://www.ghibli.jp/gallery/kokurikozaka037.jpg
        http://www.ghibli.jp/gallery/kokurikozaka038.jpg
        http://www.ghibli.jp/gallery/kokurikozaka039.jpg
        http://www.ghibli.jp/gallery/kokurikozaka040.jpg
        http://www.ghibli.jp/gallery/kokurikozaka041.jpg
        http://www.ghibli.jp/gallery/kokurikozaka042.jpg
        http://www.ghibli.jp/gallery/kokurikozaka043.jpg
        http://www.ghibli.jp/gallery/kokurikozaka044.jpg
        http://www.ghibli.jp/gallery/kokurikozaka045.jpg
        http://www.ghibli.jp/gallery/kokurikozaka046.jpg
        http://www.ghibli.jp/gallery/kokurikozaka047.jpg
        http://www.ghibli.jp/gallery/kokurikozaka048.jpg
        http://www.ghibli.jp/gallery/kokurikozaka049.jpg
        http://www.ghibli.jp/gallery/kokurikozaka050.jpg

        http://www.ghibli.jp/gallery/karigurashi001.jpg
        http://www.ghibli.jp/gallery/karigurashi002.jpg
        http://www.ghibli.jp/gallery/karigurashi003.jpg
        http://www.ghibli.jp/gallery/karigurashi004.jpg
        http://www.ghibli.jp/gallery/karigurashi005.jpg
        http://www.ghibli.jp/gallery/karigurashi006.jpg
        http://www.ghibli.jp/gallery/karigurashi007.jpg
        http://www.ghibli.jp/gallery/karigurashi008.jpg
        http://www.ghibli.jp/gallery/karigurashi009.jpg
        http://www.ghibli.jp/gallery/karigurashi010.jpg
        http://www.ghibli.jp/gallery/karigurashi011.jpg
        http://www.ghibli.jp/gallery/karigurashi012.jpg
        http://www.ghibli.jp/gallery/karigurashi013.jpg
        http://www.ghibli.jp/gallery/karigurashi014.jpg
        http://www.ghibli.jp/gallery/karigurashi015.jpg
        http://www.ghibli.jp/gallery/karigurashi016.jpg
        http://www.ghibli.jp/gallery/karigurashi017.jpg
        http://www.ghibli.jp/gallery/karigurashi018.jpg
        http://www.ghibli.jp/gallery/karigurashi019.jpg
        http://www.ghibli.jp/gallery/karigurashi020.jpg
        http://www.ghibli.jp/gallery/karigurashi021.jpg
        http://www.ghibli.jp/gallery/karigurashi022.jpg
        http://www.ghibli.jp/gallery/karigurashi023.jpg
        http://www.ghibli.jp/gallery/karigurashi024.jpg
        http://www.ghibli.jp/gallery/karigurashi025.jpg
        http://www.ghibli.jp/gallery/karigurashi026.jpg
        http://www.ghibli.jp/gallery/karigurashi027.jpg
        http://www.ghibli.jp/gallery/karigurashi028.jpg
        http://www.ghibli.jp/gallery/karigurashi029.jpg
        http://www.ghibli.jp/gallery/karigurashi030.jpg
        http://www.ghibli.jp/gallery/karigurashi031.jpg
        http://www.ghibli.jp/gallery/karigurashi032.jpg
        http://www.ghibli.jp/gallery/karigurashi033.jpg
        http://www.ghibli.jp/gallery/karigurashi034.jpg
        http://www.ghibli.jp/gallery/karigurashi035.jpg
        http://www.ghibli.jp/gallery/karigurashi036.jpg
        http://www.ghibli.jp/gallery/karigurashi037.jpg
        http://www.ghibli.jp/gallery/karigurashi038.jpg
        http://www.ghibli.jp/gallery/karigurashi039.jpg
        http://www.ghibli.jp/gallery/karigurashi040.jpg
        http://www.ghibli.jp/gallery/karigurashi041.jpg
        http://www.ghibli.jp/gallery/karigurashi042.jpg
        http://www.ghibli.jp/gallery/karigurashi043.jpg
        http://www.ghibli.jp/gallery/karigurashi044.jpg
        http://www.ghibli.jp/gallery/karigurashi045.jpg
        http://www.ghibli.jp/gallery/karigurashi046.jpg
        http://www.ghibli.jp/gallery/karigurashi047.jpg
        http://www.ghibli.jp/gallery/karigurashi048.jpg
        http://www.ghibli.jp/gallery/karigurashi049.jpg
        http://www.ghibli.jp/gallery/karigurashi050.jpg

        http://www.ghibli.jp/gallery/ponyo001.jpg
        http://www.ghibli.jp/gallery/ponyo002.jpg
        http://www.ghibli.jp/gallery/ponyo003.jpg
        http://www.ghibli.jp/gallery/ponyo004.jpg
        http://www.ghibli.jp/gallery/ponyo005.jpg
        http://www.ghibli.jp/gallery/ponyo006.jpg
        http://www.ghibli.jp/gallery/ponyo007.jpg
        http://www.ghibli.jp/gallery/ponyo008.jpg
        http://www.ghibli.jp/gallery/ponyo009.jpg
        http://www.ghibli.jp/gallery/ponyo010.jpg
        http://www.ghibli.jp/gallery/ponyo011.jpg
        http://www.ghibli.jp/gallery/ponyo012.jpg
        http://www.ghibli.jp/gallery/ponyo013.jpg
        http://www.ghibli.jp/gallery/ponyo014.jpg
        http://www.ghibli.jp/gallery/ponyo015.jpg
        http://www.ghibli.jp/gallery/ponyo016.jpg
        http://www.ghibli.jp/gallery/ponyo017.jpg
        http://www.ghibli.jp/gallery/ponyo018.jpg
        http://www.ghibli.jp/gallery/ponyo019.jpg
        http://www.ghibli.jp/gallery/ponyo020.jpg
        http://www.ghibli.jp/gallery/ponyo021.jpg
        http://www.ghibli.jp/gallery/ponyo022.jpg
        http://www.ghibli.jp/gallery/ponyo023.jpg
        http://www.ghibli.jp/gallery/ponyo024.jpg
        http://www.ghibli.jp/gallery/ponyo025.jpg
        http://www.ghibli.jp/gallery/ponyo026.jpg
        http://www.ghibli.jp/gallery/ponyo027.jpg
        http://www.ghibli.jp/gallery/ponyo028.jpg
        http://www.ghibli.jp/gallery/ponyo029.jpg
        http://www.ghibli.jp/gallery/ponyo030.jpg
        http://www.ghibli.jp/gallery/ponyo031.jpg
        http://www.ghibli.jp/gallery/ponyo032.jpg
        http://www.ghibli.jp/gallery/ponyo033.jpg
        http://www.ghibli.jp/gallery/ponyo034.jpg
        http://www.ghibli.jp/gallery/ponyo035.jpg
        http://www.ghibli.jp/gallery/ponyo036.jpg
        http://www.ghibli.jp/gallery/ponyo037.jpg
        http://www.ghibli.jp/gallery/ponyo038.jpg
        http://www.ghibli.jp/gallery/ponyo039.jpg
        http://www.ghibli.jp/gallery/ponyo040.jpg
        http://www.ghibli.jp/gallery/ponyo041.jpg
        http://www.ghibli.jp/gallery/ponyo042.jpg
        http://www.ghibli.jp/gallery/ponyo043.jpg
        http://www.ghibli.jp/gallery/ponyo044.jpg
        http://www.ghibli.jp/gallery/ponyo045.jpg
        http://www.ghibli.jp/gallery/ponyo046.jpg
        http://www.ghibli.jp/gallery/ponyo047.jpg
        http://www.ghibli.jp/gallery/ponyo048.jpg
        http://www.ghibli.jp/gallery/ponyo049.jpg
        http://www.ghibli.jp/gallery/ponyo050.jpg

        http://www.ghibli.jp/gallery/ged001.jpg
        http://www.ghibli.jp/gallery/ged002.jpg
        http://www.ghibli.jp/gallery/ged003.jpg
        http://www.ghibli.jp/gallery/ged004.jpg
        http://www.ghibli.jp/gallery/ged005.jpg
        http://www.ghibli.jp/gallery/ged006.jpg
        http://www.ghibli.jp/gallery/ged007.jpg
        http://www.ghibli.jp/gallery/ged008.jpg
        http://www.ghibli.jp/gallery/ged009.jpg
        http://www.ghibli.jp/gallery/ged010.jpg
        http://www.ghibli.jp/gallery/ged011.jpg
        http://www.ghibli.jp/gallery/ged012.jpg
        http://www.ghibli.jp/gallery/ged013.jpg
        http://www.ghibli.jp/gallery/ged014.jpg
        http://www.ghibli.jp/gallery/ged015.jpg
        http://www.ghibli.jp/gallery/ged016.jpg
        http://www.ghibli.jp/gallery/ged017.jpg
        http://www.ghibli.jp/gallery/ged018.jpg
        http://www.ghibli.jp/gallery/ged019.jpg
        http://www.ghibli.jp/gallery/ged020.jpg
        http://www.ghibli.jp/gallery/ged021.jpg
        http://www.ghibli.jp/gallery/ged022.jpg
        http://www.ghibli.jp/gallery/ged023.jpg
        http://www.ghibli.jp/gallery/ged024.jpg
        http://www.ghibli.jp/gallery/ged025.jpg
        http://www.ghibli.jp/gallery/ged026.jpg
        http://www.ghibli.jp/gallery/ged027.jpg
        http://www.ghibli.jp/gallery/ged028.jpg
        http://www.ghibli.jp/gallery/ged029.jpg
        http://www.ghibli.jp/gallery/ged030.jpg
        http://www.ghibli.jp/gallery/ged031.jpg
        http://www.ghibli.jp/gallery/ged032.jpg
        http://www.ghibli.jp/gallery/ged033.jpg
        http://www.ghibli.jp/gallery/ged034.jpg
        http://www.ghibli.jp/gallery/ged035.jpg
        http://www.ghibli.jp/gallery/ged036.jpg
        http://www.ghibli.jp/gallery/ged037.jpg
        http://www.ghibli.jp/gallery/ged038.jpg
        http://www.ghibli.jp/gallery/ged039.jpg
        http://www.ghibli.jp/gallery/ged040.jpg
        http://www.ghibli.jp/gallery/ged041.jpg
        http://www.ghibli.jp/gallery/ged042.jpg
        http://www.ghibli.jp/gallery/ged043.jpg
        http://www.ghibli.jp/gallery/ged044.jpg
        http://www.ghibli.jp/gallery/ged045.jpg
        http://www.ghibli.jp/gallery/ged046.jpg
        http://www.ghibli.jp/gallery/ged047.jpg
        http://www.ghibli.jp/gallery/ged048.jpg
        http://www.ghibli.jp/gallery/ged049.jpg
        http://www.ghibli.jp/gallery/ged050.jpg

        http://www.ghibli.jp/gallery/chihiro001.jpg
        http://www.ghibli.jp/gallery/chihiro002.jpg
        http://www.ghibli.jp/gallery/chihiro003.jpg
        http://www.ghibli.jp/gallery/chihiro004.jpg
        http://www.ghibli.jp/gallery/chihiro005.jpg
        http://www.ghibli.jp/gallery/chihiro006.jpg
        http://www.ghibli.jp/gallery/chihiro007.jpg
        http://www.ghibli.jp/gallery/chihiro008.jpg
        http://www.ghibli.jp/gallery/chihiro009.jpg
        http://www.ghibli.jp/gallery/chihiro010.jpg
        http://www.ghibli.jp/gallery/chihiro011.jpg
        http://www.ghibli.jp/gallery/chihiro012.jpg
        http://www.ghibli.jp/gallery/chihiro013.jpg
        http://www.ghibli.jp/gallery/chihiro014.jpg
        http://www.ghibli.jp/gallery/chihiro015.jpg
        http://www.ghibli.jp/gallery/chihiro016.jpg
        http://www.ghibli.jp/gallery/chihiro017.jpg
        http://www.ghibli.jp/gallery/chihiro018.jpg
        http://www.ghibli.jp/gallery/chihiro019.jpg
        http://www.ghibli.jp/gallery/chihiro020.jpg
        http://www.ghibli.jp/gallery/chihiro021.jpg
        http://www.ghibli.jp/gallery/chihiro022.jpg
        http://www.ghibli.jp/gallery/chihiro023.jpg
        http://www.ghibli.jp/gallery/chihiro024.jpg
        http://www.ghibli.jp/gallery/chihiro025.jpg
        http://www.ghibli.jp/gallery/chihiro026.jpg
        http://www.ghibli.jp/gallery/chihiro027.jpg
        http://www.ghibli.jp/gallery/chihiro028.jpg
        http://www.ghibli.jp/gallery/chihiro029.jpg
        http://www.ghibli.jp/gallery/chihiro030.jpg
        http://www.ghibli.jp/gallery/chihiro031.jpg
        http://www.ghibli.jp/gallery/chihiro032.jpg
        http://www.ghibli.jp/gallery/chihiro033.jpg
        http://www.ghibli.jp/gallery/chihiro034.jpg
        http://www.ghibli.jp/gallery/chihiro035.jpg
        http://www.ghibli.jp/gallery/chihiro036.jpg
        http://www.ghibli.jp/gallery/chihiro037.jpg
        http://www.ghibli.jp/gallery/chihiro038.jpg
        http://www.ghibli.jp/gallery/chihiro039.jpg
        http://www.ghibli.jp/gallery/chihiro040.jpg
        http://www.ghibli.jp/gallery/chihiro041.jpg
        http://www.ghibli.jp/gallery/chihiro042.jpg
        http://www.ghibli.jp/gallery/chihiro043.jpg
        http://www.ghibli.jp/gallery/chihiro044.jpg
        http://www.ghibli.jp/gallery/chihiro045.jpg
        http://www.ghibli.jp/gallery/chihiro046.jpg
        http://www.ghibli.jp/gallery/chihiro047.jpg
        http://www.ghibli.jp/gallery/chihiro048.jpg
        http://www.ghibli.jp/gallery/chihiro049.jpg
        http://www.ghibli.jp/gallery/chihiro050.jpg

        http://www.ghibli.jp/gallery/howl001.jpg
        http://www.ghibli.jp/gallery/howl002.jpg
        http://www.ghibli.jp/gallery/howl003.jpg
        http://www.ghibli.jp/gallery/howl004.jpg
        http://www.ghibli.jp/gallery/howl005.jpg
        http://www.ghibli.jp/gallery/howl006.jpg
        http://www.ghibli.jp/gallery/howl007.jpg
        http://www.ghibli.jp/gallery/howl008.jpg
        http://www.ghibli.jp/gallery/howl009.jpg
        http://www.ghibli.jp/gallery/howl010.jpg
        http://www.ghibli.jp/gallery/howl011.jpg
        http://www.ghibli.jp/gallery/howl012.jpg
        http://www.ghibli.jp/gallery/howl013.jpg
        http://www.ghibli.jp/gallery/howl014.jpg
        http://www.ghibli.jp/gallery/howl015.jpg
        http://www.ghibli.jp/gallery/howl016.jpg
        http://www.ghibli.jp/gallery/howl017.jpg
        http://www.ghibli.jp/gallery/howl018.jpg
        http://www.ghibli.jp/gallery/howl019.jpg
        http://www.ghibli.jp/gallery/howl020.jpg
        http://www.ghibli.jp/gallery/howl021.jpg
        http://www.ghibli.jp/gallery/howl022.jpg
        http://www.ghibli.jp/gallery/howl023.jpg
        http://www.ghibli.jp/gallery/howl024.jpg
        http://www.ghibli.jp/gallery/howl025.jpg
        http://www.ghibli.jp/gallery/howl026.jpg
        http://www.ghibli.jp/gallery/howl027.jpg
        http://www.ghibli.jp/gallery/howl028.jpg
        http://www.ghibli.jp/gallery/howl029.jpg
        http://www.ghibli.jp/gallery/howl030.jpg
        http://www.ghibli.jp/gallery/howl031.jpg
        http://www.ghibli.jp/gallery/howl032.jpg
        http://www.ghibli.jp/gallery/howl033.jpg
        http://www.ghibli.jp/gallery/howl034.jpg
        http://www.ghibli.jp/gallery/howl035.jpg
        http://www.ghibli.jp/gallery/howl036.jpg
        http://www.ghibli.jp/gallery/howl037.jpg
        http://www.ghibli.jp/gallery/howl038.jpg
        http://www.ghibli.jp/gallery/howl039.jpg
        http://www.ghibli.jp/gallery/howl040.jpg
        http://www.ghibli.jp/gallery/howl041.jpg
        http://www.ghibli.jp/gallery/howl042.jpg
        http://www.ghibli.jp/gallery/howl043.jpg
        http://www.ghibli.jp/gallery/howl044.jpg
        http://www.ghibli.jp/gallery/howl045.jpg
        http://www.ghibli.jp/gallery/howl046.jpg
        http://www.ghibli.jp/gallery/howl047.jpg
        http://www.ghibli.jp/gallery/howl048.jpg
        http://www.ghibli.jp/gallery/howl049.jpg
        http://www.ghibli.jp/gallery/howl050.jpg

        http://www.ghibli.jp/gallery/baron001.jpg
        http://www.ghibli.jp/gallery/baron002.jpg
        http://www.ghibli.jp/gallery/baron003.jpg
        http://www.ghibli.jp/gallery/baron004.jpg
        http://www.ghibli.jp/gallery/baron005.jpg
        http://www.ghibli.jp/gallery/baron006.jpg
        http://www.ghibli.jp/gallery/baron007.jpg
        http://www.ghibli.jp/gallery/baron008.jpg
        http://www.ghibli.jp/gallery/baron009.jpg
        http://www.ghibli.jp/gallery/baron010.jpg
        http://www.ghibli.jp/gallery/baron011.jpg
        http://www.ghibli.jp/gallery/baron012.jpg
        http://www.ghibli.jp/gallery/baron013.jpg
        http://www.ghibli.jp/gallery/baron014.jpg
        http://www.ghibli.jp/gallery/baron015.jpg
        http://www.ghibli.jp/gallery/baron016.jpg
        http://www.ghibli.jp/gallery/baron017.jpg
        http://www.ghibli.jp/gallery/baron018.jpg
        http://www.ghibli.jp/gallery/baron019.jpg
        http://www.ghibli.jp/gallery/baron020.jpg
        http://www.ghibli.jp/gallery/baron021.jpg
        http://www.ghibli.jp/gallery/baron022.jpg
        http://www.ghibli.jp/gallery/baron023.jpg
        http://www.ghibli.jp/gallery/baron024.jpg
        http://www.ghibli.jp/gallery/baron025.jpg
        http://www.ghibli.jp/gallery/baron026.jpg
        http://www.ghibli.jp/gallery/baron027.jpg
        http://www.ghibli.jp/gallery/baron028.jpg
        http://www.ghibli.jp/gallery/baron029.jpg
        http://www.ghibli.jp/gallery/baron030.jpg
        http://www.ghibli.jp/gallery/baron031.jpg
        http://www.ghibli.jp/gallery/baron032.jpg
        http://www.ghibli.jp/gallery/baron033.jpg
        http://www.ghibli.jp/gallery/baron034.jpg
        http://www.ghibli.jp/gallery/baron035.jpg
        http://www.ghibli.jp/gallery/baron036.jpg
        http://www.ghibli.jp/gallery/baron037.jpg
        http://www.ghibli.jp/gallery/baron038.jpg
        http://www.ghibli.jp/gallery/baron039.jpg
        http://www.ghibli.jp/gallery/baron040.jpg
        http://www.ghibli.jp/gallery/baron041.jpg
        http://www.ghibli.jp/gallery/baron042.jpg
        http://www.ghibli.jp/gallery/baron043.jpg
        http://www.ghibli.jp/gallery/baron044.jpg
        http://www.ghibli.jp/gallery/baron045.jpg
        http://www.ghibli.jp/gallery/baron046.jpg
        http://www.ghibli.jp/gallery/baron047.jpg
        http://www.ghibli.jp/gallery/baron048.jpg
        http://www.ghibli.jp/gallery/baron049.jpg
        http://www.ghibli.jp/gallery/baron050.jpg

        http://www.ghibli.jp/gallery/ghiblies001.jpg
        http://www.ghibli.jp/gallery/ghiblies002.jpg
        http://www.ghibli.jp/gallery/ghiblies003.jpg
        http://www.ghibli.jp/gallery/ghiblies004.jpg
        http://www.ghibli.jp/gallery/ghiblies005.jpg
        http://www.ghibli.jp/gallery/ghiblies006.jpg
        http://www.ghibli.jp/gallery/ghiblies007.jpg
        http://www.ghibli.jp/gallery/ghiblies008.jpg
        http://www.ghibli.jp/gallery/ghiblies009.jpg
        http://www.ghibli.jp/gallery/ghiblies010.jpg
        http://www.ghibli.jp/gallery/ghiblies011.jpg
        http://www.ghibli.jp/gallery/ghiblies012.jpg
        http://www.ghibli.jp/gallery/ghiblies013.jpg
        http://www.ghibli.jp/gallery/ghiblies014.jpg
        http://www.ghibli.jp/gallery/ghiblies015.jpg
        http://www.ghibli.jp/gallery/ghiblies016.jpg
        http://www.ghibli.jp/gallery/ghiblies017.jpg
        http://www.ghibli.jp/gallery/ghiblies018.jpg
        http://www.ghibli.jp/gallery/ghiblies019.jpg
        http://www.ghibli.jp/gallery/ghiblies020.jpg
        http://www.ghibli.jp/gallery/ghiblies021.jpg
        http://www.ghibli.jp/gallery/ghiblies022.jpg
        http://www.ghibli.jp/gallery/ghiblies023.jpg
        http://www.ghibli.jp/gallery/ghiblies024.jpg
        http://www.ghibli.jp/gallery/ghiblies025.jpg
        http://www.ghibli.jp/gallery/ghiblies026.jpg
        http://www.ghibli.jp/gallery/ghiblies027.jpg
        http://www.ghibli.jp/gallery/ghiblies028.jpg
        http://www.ghibli.jp/gallery/ghiblies029.jpg
        http://www.ghibli.jp/gallery/ghiblies030.jpg
        http://www.ghibli.jp/gallery/ghiblies031.jpg
        http://www.ghibli.jp/gallery/ghiblies032.jpg
        http://www.ghibli.jp/gallery/ghiblies033.jpg
        http://www.ghibli.jp/gallery/ghiblies034.jpg
        http://www.ghibli.jp/gallery/ghiblies035.jpg
        http://www.ghibli.jp/gallery/ghiblies036.jpg
        http://www.ghibli.jp/gallery/ghiblies037.jpg
        http://www.ghibli.jp/gallery/ghiblies038.jpg
        http://www.ghibli.jp/gallery/ghiblies039.jpg
        http://www.ghibli.jp/gallery/ghiblies040.jpg
        http://www.ghibli.jp/gallery/ghiblies041.jpg
        http://www.ghibli.jp/gallery/ghiblies042.jpg
        http://www.ghibli.jp/gallery/ghiblies043.jpg
        http://www.ghibli.jp/gallery/ghiblies044.jpg
        http://www.ghibli.jp/gallery/ghiblies045.jpg
        http://www.ghibli.jp/gallery/ghiblies046.jpg
        http://www.ghibli.jp/gallery/ghiblies047.jpg
        http://www.ghibli.jp/gallery/ghiblies048.jpg
        http://www.ghibli.jp/gallery/ghiblies049.jpg
        http://www.ghibli.jp/gallery/ghiblies050.jpg

        http://www.ghibli.jp/gallery/yamada001.jpg
        http://www.ghibli.jp/gallery/yamada002.jpg
        http://www.ghibli.jp/gallery/yamada003.jpg
        http://www.ghibli.jp/gallery/yamada004.jpg
        http://www.ghibli.jp/gallery/yamada005.jpg
        http://www.ghibli.jp/gallery/yamada006.jpg
        http://www.ghibli.jp/gallery/yamada007.jpg
        http://www.ghibli.jp/gallery/yamada008.jpg
        http://www.ghibli.jp/gallery/yamada009.jpg
        http://www.ghibli.jp/gallery/yamada010.jpg
        http://www.ghibli.jp/gallery/yamada011.jpg
        http://www.ghibli.jp/gallery/yamada012.jpg
        http://www.ghibli.jp/gallery/yamada013.jpg
        http://www.ghibli.jp/gallery/yamada014.jpg
        http://www.ghibli.jp/gallery/yamada015.jpg
        http://www.ghibli.jp/gallery/yamada016.jpg
        http://www.ghibli.jp/gallery/yamada017.jpg
        http://www.ghibli.jp/gallery/yamada018.jpg
        http://www.ghibli.jp/gallery/yamada019.jpg
        http://www.ghibli.jp/gallery/yamada020.jpg
        http://www.ghibli.jp/gallery/yamada021.jpg
        http://www.ghibli.jp/gallery/yamada022.jpg
        http://www.ghibli.jp/gallery/yamada023.jpg
        http://www.ghibli.jp/gallery/yamada024.jpg
        http://www.ghibli.jp/gallery/yamada025.jpg
        http://www.ghibli.jp/gallery/yamada026.jpg
        http://www.ghibli.jp/gallery/yamada027.jpg
        http://www.ghibli.jp/gallery/yamada028.jpg
        http://www.ghibli.jp/gallery/yamada029.jpg
        http://www.ghibli.jp/gallery/yamada030.jpg
        http://www.ghibli.jp/gallery/yamada031.jpg
        http://www.ghibli.jp/gallery/yamada032.jpg
        http://www.ghibli.jp/gallery/yamada033.jpg
        http://www.ghibli.jp/gallery/yamada034.jpg
        http://www.ghibli.jp/gallery/yamada035.jpg
        http://www.ghibli.jp/gallery/yamada036.jpg
        http://www.ghibli.jp/gallery/yamada037.jpg
        http://www.ghibli.jp/gallery/yamada038.jpg
        http://www.ghibli.jp/gallery/yamada039.jpg
        http://www.ghibli.jp/gallery/yamada040.jpg
        http://www.ghibli.jp/gallery/yamada041.jpg
        http://www.ghibli.jp/gallery/yamada042.jpg
        http://www.ghibli.jp/gallery/yamada043.jpg
        http://www.ghibli.jp/gallery/yamada044.jpg
        http://www.ghibli.jp/gallery/yamada045.jpg
        http://www.ghibli.jp/gallery/yamada046.jpg
        http://www.ghibli.jp/gallery/yamada047.jpg
        http://www.ghibli.jp/gallery/yamada048.jpg
        http://www.ghibli.jp/gallery/yamada049.jpg
        http://www.ghibli.jp/gallery/yamada050.jpg

        http://www.ghibli.jp/gallery/mononoke001.jpg
        http://www.ghibli.jp/gallery/mononoke002.jpg
        http://www.ghibli.jp/gallery/mononoke003.jpg
        http://www.ghibli.jp/gallery/mononoke004.jpg
        http://www.ghibli.jp/gallery/mononoke005.jpg
        http://www.ghibli.jp/gallery/mononoke006.jpg
        http://www.ghibli.jp/gallery/mononoke007.jpg
        http://www.ghibli.jp/gallery/mononoke008.jpg
        http://www.ghibli.jp/gallery/mononoke009.jpg
        http://www.ghibli.jp/gallery/mononoke010.jpg
        http://www.ghibli.jp/gallery/mononoke011.jpg
        http://www.ghibli.jp/gallery/mononoke012.jpg
        http://www.ghibli.jp/gallery/mononoke013.jpg
        http://www.ghibli.jp/gallery/mononoke014.jpg
        http://www.ghibli.jp/gallery/mononoke015.jpg
        http://www.ghibli.jp/gallery/mononoke016.jpg
        http://www.ghibli.jp/gallery/mononoke017.jpg
        http://www.ghibli.jp/gallery/mononoke018.jpg
        http://www.ghibli.jp/gallery/mononoke019.jpg
        http://www.ghibli.jp/gallery/mononoke020.jpg
        http://www.ghibli.jp/gallery/mononoke021.jpg
        http://www.ghibli.jp/gallery/mononoke022.jpg
        http://www.ghibli.jp/gallery/mononoke023.jpg
        http://www.ghibli.jp/gallery/mononoke024.jpg
        http://www.ghibli.jp/gallery/mononoke025.jpg
        http://www.ghibli.jp/gallery/mononoke026.jpg
        http://www.ghibli.jp/gallery/mononoke027.jpg
        http://www.ghibli.jp/gallery/mononoke028.jpg
        http://www.ghibli.jp/gallery/mononoke029.jpg
        http://www.ghibli.jp/gallery/mononoke030.jpg
        http://www.ghibli.jp/gallery/mononoke031.jpg
        http://www.ghibli.jp/gallery/mononoke032.jpg
        http://www.ghibli.jp/gallery/mononoke033.jpg
        http://www.ghibli.jp/gallery/mononoke034.jpg
        http://www.ghibli.jp/gallery/mononoke035.jpg
        http://www.ghibli.jp/gallery/mononoke036.jpg
        http://www.ghibli.jp/gallery/mononoke037.jpg
        http://www.ghibli.jp/gallery/mononoke038.jpg
        http://www.ghibli.jp/gallery/mononoke039.jpg
        http://www.ghibli.jp/gallery/mononoke040.jpg
        http://www.ghibli.jp/gallery/mononoke041.jpg
        http://www.ghibli.jp/gallery/mononoke042.jpg
        http://www.ghibli.jp/gallery/mononoke043.jpg
        http://www.ghibli.jp/gallery/mononoke044.jpg
        http://www.ghibli.jp/gallery/mononoke045.jpg
        http://www.ghibli.jp/gallery/mononoke046.jpg
        http://www.ghibli.jp/gallery/mononoke047.jpg
        http://www.ghibli.jp/gallery/mononoke048.jpg
        http://www.ghibli.jp/gallery/mononoke049.jpg
        http://www.ghibli.jp/gallery/mononoke050.jpg

        http://www.ghibli.jp/gallery/mimi001.jpg
        http://www.ghibli.jp/gallery/mimi002.jpg
        http://www.ghibli.jp/gallery/mimi003.jpg
        http://www.ghibli.jp/gallery/mimi004.jpg
        http://www.ghibli.jp/gallery/mimi005.jpg
        http://www.ghibli.jp/gallery/mimi006.jpg
        http://www.ghibli.jp/gallery/mimi007.jpg
        http://www.ghibli.jp/gallery/mimi008.jpg
        http://www.ghibli.jp/gallery/mimi009.jpg
        http://www.ghibli.jp/gallery/mimi010.jpg
        http://www.ghibli.jp/gallery/mimi011.jpg
        http://www.ghibli.jp/gallery/mimi012.jpg
        http://www.ghibli.jp/gallery/mimi013.jpg
        http://www.ghibli.jp/gallery/mimi014.jpg
        http://www.ghibli.jp/gallery/mimi015.jpg
        http://www.ghibli.jp/gallery/mimi016.jpg
        http://www.ghibli.jp/gallery/mimi017.jpg
        http://www.ghibli.jp/gallery/mimi018.jpg
        http://www.ghibli.jp/gallery/mimi019.jpg
        http://www.ghibli.jp/gallery/mimi020.jpg
        http://www.ghibli.jp/gallery/mimi021.jpg
        http://www.ghibli.jp/gallery/mimi022.jpg
        http://www.ghibli.jp/gallery/mimi023.jpg
        http://www.ghibli.jp/gallery/mimi024.jpg
        http://www.ghibli.jp/gallery/mimi025.jpg
        http://www.ghibli.jp/gallery/mimi026.jpg
        http://www.ghibli.jp/gallery/mimi027.jpg
        http://www.ghibli.jp/gallery/mimi028.jpg
        http://www.ghibli.jp/gallery/mimi029.jpg
        http://www.ghibli.jp/gallery/mimi030.jpg
        http://www.ghibli.jp/gallery/mimi031.jpg
        http://www.ghibli.jp/gallery/mimi032.jpg
        http://www.ghibli.jp/gallery/mimi033.jpg
        http://www.ghibli.jp/gallery/mimi034.jpg
        http://www.ghibli.jp/gallery/mimi035.jpg
        http://www.ghibli.jp/gallery/mimi036.jpg
        http://www.ghibli.jp/gallery/mimi037.jpg
        http://www.ghibli.jp/gallery/mimi038.jpg
        http://www.ghibli.jp/gallery/mimi039.jpg
        http://www.ghibli.jp/gallery/mimi040.jpg
        http://www.ghibli.jp/gallery/mimi041.jpg
        http://www.ghibli.jp/gallery/mimi042.jpg
        http://www.ghibli.jp/gallery/mimi043.jpg
        http://www.ghibli.jp/gallery/mimi044.jpg
        http://www.ghibli.jp/gallery/mimi045.jpg
        http://www.ghibli.jp/gallery/mimi046.jpg
        http://www.ghibli.jp/gallery/mimi047.jpg
        http://www.ghibli.jp/gallery/mimi048.jpg
        http://www.ghibli.jp/gallery/mimi049.jpg
        http://www.ghibli.jp/gallery/mimi050.jpg
      ]

      on /ghibli/, name: 'ghibli', description: 'Show a random ghibli picture'

      def ghibli(message)
        message.reply(PICTURES.sample)
      end
    end
  end
end
